export const data = [
  { address: '경상북도 포항시 남구 중흥로', nightAccidentCount: 28, trafficCount: 624, badLane: 14, riskLevel: 29 },
  { address: '경상북도 포항시 북구 양학로', nightAccidentCount: 19, trafficCount: 812, badLane: 12, riskLevel: 33 },
  { address: '경상북도 포항시 남구 상도동길', nightAccidentCount: 32, trafficCount: 567, badLane: 16, riskLevel: 28 },
  { address: '경상북도 포항시 북구 두호로', nightAccidentCount: 41, trafficCount: 499, badLane: 10, riskLevel: 26 },
  { address: '경상북도 포항시 남구 해맞이길', nightAccidentCount: 25, trafficCount: 729, badLane: 18, riskLevel: 33 },
  {
    address: '경상북도 포항시 북구 죽도시장길',
    nightAccidentCount: 16,
    trafficCount: 812,
    badLane: 9,
    riskLevel: 32,
  },
  { address: '경상북도 포항시 남구 송도로', nightAccidentCount: 21, trafficCount: 421, badLane: 14, riskLevel: 21 },
  { address: '경상북도 포항시 북구 대흥로', nightAccidentCount: 39, trafficCount: 768, badLane: 19, riskLevel: 37 },
  { address: '경상북도 포항시 남구 신덕로', nightAccidentCount: 22, trafficCount: 590, badLane: 15, riskLevel: 27 },
  { address: '경상북도 포항시 북구 흥해읍로', nightAccidentCount: 18, trafficCount: 780, badLane: 10, riskLevel: 32 },
  { address: '경상북도 포항시 남구 오천로', nightAccidentCount: 12, trafficCount: 432, badLane: 5, riskLevel: 18 },
  { address: '경상북도 포항시 북구 장성로', nightAccidentCount: 24, trafficCount: 523, badLane: 14, riskLevel: 25 },
  { address: '경상북도 포항시 남구 청림로', nightAccidentCount: 74, trafficCount: 654, badLane: 23, riskLevel: 39 },
  { address: '경상북도 포항시 북구 학잠로', nightAccidentCount: 35, trafficCount: 737, badLane: 1, riskLevel: 31 },
  { address: '경상북도 포항시 남구 구룡포로', nightAccidentCount: 63, trafficCount: 131, badLane: 2, riskLevel: 15 },
  { address: '경상북도 포항시 북구 중앙로', nightAccidentCount: 62, trafficCount: 13, badLane: 6, riskLevel: 11 },
  { address: '경상북도 포항시 남구 대이로', nightAccidentCount: 42, trafficCount: 41, badLane: 8, riskLevel: 10 },
  { address: '경상북도 포항시 북구 용흥로', nightAccidentCount: 2, trafficCount: 21, badLane: 2, riskLevel: 1 },
  { address: '경상북도 포항시 남구 장기로', nightAccidentCount: 64, trafficCount: 451, badLane: 1, riskLevel: 25 },
  { address: '경상북도 포항시 북구 항구로', nightAccidentCount: 2, trafficCount: 21, badLane: 4, riskLevel: 2 },
  { address: '경상북도 포항시 남구 흥해로', nightAccidentCount: 1, trafficCount: 46, badLane: 6, riskLevel: 3 },
  { address: '경상북도 포항시 북구 죽도시장길', nightAccidentCount: 6, trafficCount: 85, badLane: 3, riskLevel: 5 },
  { address: '경상북도 포항시 남구 송도시장길', nightAccidentCount: 7, trafficCount: 282, badLane: 7, riskLevel: 12 },
  { address: '경상북도 포항시 북구 대이로', nightAccidentCount: 3, trafficCount: 632, badLane: 9, riskLevel: 24 },
  {
    address: '경상북도 포항시 남구 중앙상가로',
    nightAccidentCount: 75,
    trafficCount: 246,
    badLane: 0,
    riskLevel: 20,
  },
  {
    address: '경상북도 포항시 북구 용흥시장길',
    nightAccidentCount: 62,
    trafficCount: 234,
    badLane: 5,
    riskLevel: 19,
  },
  { address: '경상북도 포항시 남구 대잠로', nightAccidentCount: 37, trafficCount: 134, badLane: 4, riskLevel: 11 },
  { address: '경상북도 포항시 북구 해도로', nightAccidentCount: 28, trafficCount: 631, badLane: 23, riskLevel: 31 },
  { address: '경상북도 포항시 남구 동해로', nightAccidentCount: 95, trafficCount: 23, badLane: 46, riskLevel: 27 },
  { address: '경상북도 포항시 북구 오천시장길', nightAccidentCount: 56, trafficCount: 63, badLane: 1, riskLevel: 11 },
  { address: '경상북도 포항시 남구 학산로', nightAccidentCount: 2, trafficCount: 74, badLane: 3, riskLevel: 4 },
  { address: '경상북도 포항시 북구 죽도해안로', nightAccidentCount: 6, trafficCount: 85, badLane: 5, riskLevel: 5 },
  { address: '경상북도 포항시 남구 환호로', nightAccidentCount: 52, trafficCount: 25, badLane: 9, riskLevel: 11 },
  { address: '경상북도 포항시 북구 장량로', nightAccidentCount: 83, trafficCount: 47, badLane: 4, riskLevel: 15 },
  { address: '경상북도 포항시 남구 창포로', nightAccidentCount: 34, trafficCount: 58, badLane: 6, riskLevel: 9 },
  { address: '경상북도 포항시 북구 우현로', nightAccidentCount: 324, trafficCount: 5, badLane: 9, riskLevel: 52 },
  { address: '경상북도 포항시 남구 지곡로', nightAccidentCount: 76, trafficCount: 5, badLane: 0, riskLevel: 43 },
  { address: '경상북도 포항시 북구 동빈로', nightAccidentCount: 42, trafficCount: 352, badLane: 2, riskLevel: 36 },
  { address: '경상북도 포항시 남구 연일로', nightAccidentCount: 56, trafficCount: 24, badLane: 5, riskLevel: 33 },
  {
    address: '경상북도 포항시 북구 중앙상가길',
    nightAccidentCount: 26,
    trafficCount: 676,
    badLane: 7,
    riskLevel: 39,
  },
  { address: '경상북도 포항시 남구 두호로', nightAccidentCount: 72, trafficCount: 534, badLane: 3, riskLevel: 59 },
  { address: '경상북도 포항시 북구 송림로', nightAccidentCount: 2, trafficCount: 66, badLane: 0, riskLevel: 3 },
  { address: '경상북도 포항시 남구 죽도로', nightAccidentCount: 6, trafficCount: 42, badLane: 0, riskLevel: 5 },
  { address: '경상북도 포항시 북구 북부시장길', nightAccidentCount: 8, trafficCount: 16, badLane: 0, riskLevel: 5 },
  { address: '경상북도 포항시 남구 해도시장길', nightAccidentCount: 4, trafficCount: 4, badLane: 0, riskLevel: 2 },
  { address: '경상북도 포항시 북구 효자동길', nightAccidentCount: 5, trafficCount: 85, badLane: 0, riskLevel: 6 },
  { address: '경상북도 포항시 남구 대도시장길', nightAccidentCount: 7, trafficCount: 78, badLane: 0, riskLevel: 7 },
  { address: '경상북도 포항시 북구 상도로', nightAccidentCount: 2, trafficCount: 23, badLane: 0, riskLevel: 2 },
  { address: '경상북도 포항시 남구 흥해해안로', nightAccidentCount: 4, trafficCount: 63, badLane: 2, riskLevel: 5 },
  { address: '경상북도 포항시 북구 양학시장길', nightAccidentCount: 6, trafficCount: 578, badLane: 3, riskLevel: 23 },
  { address: '경상북도 포항시 남구 구룡시장길', nightAccidentCount: 32, trafficCount: 24, badLane: 5, riskLevel: 20 },
  { address: '경상북도 포항시 북구 죽도시장길', nightAccidentCount: 2, trafficCount: 889, badLane: 3, riskLevel: 32 },
  { address: '경상북도 포항시 남구 용흥해안로', nightAccidentCount: 4, trafficCount: 24, badLane: 2, riskLevel: 3 },
  { address: '경상북도 포항시 북구 우현시장길', nightAccidentCount: 2, trafficCount: 67, badLane: 5, riskLevel: 4 },
  { address: '경상북도 포항시 남구 두호해안로', nightAccidentCount: 3, trafficCount: 2, badLane: 1, riskLevel: 2 },
  { address: '경상북도 포항시 북구 대잠해안로', nightAccidentCount: 4, trafficCount: 4, badLane: 3, riskLevel: 3 },
  { address: '경상북도 포항시 남구 대송시장길', nightAccidentCount: 6, trafficCount: 85, badLane: 5, riskLevel: 7 },
  { address: '경상북도 포항시 북구 상도해안로', nightAccidentCount: 22, trafficCount: 8, badLane: 6, riskLevel: 14 },
  { address: '경상북도 포항시 남구 장기시장길', nightAccidentCount: 0, trafficCount: 794, badLane: 7, riskLevel: 29 },
  { address: '경상북도 포항시 북구 흥해시장길', nightAccidentCount: 0, trafficCount: 7, badLane: 2, riskLevel: 0 },
  { address: '경상북도 포항시 남구 송도시장로', nightAccidentCount: 9, trafficCount: 2, badLane: 6, riskLevel: 5 },
  { address: '경상북도 포항시 북구 해도해안로', nightAccidentCount: 5, trafficCount: 57, badLane: 7, riskLevel: 5 },
  { address: '경상북도 포항시 남구 오천해안로', nightAccidentCount: 4, trafficCount: 4, badLane: 2, riskLevel: 1 },
  { address: '경상북도 포항시 북구 동해시장길', nightAccidentCount: 5, trafficCount: 2, badLane: 34, riskLevel: 10 },
  { address: '경상북도 포항시 남구 장성시장길', nightAccidentCount: 25, trafficCount: 7, badLane: 21, riskLevel: 19 },
  { address: '경상북도 포항시 북구 청림시장길', nightAccidentCount: 6, trafficCount: 28, badLane: 1, riskLevel: 3 },
  { address: '경상북도 포항시 남구 송림시장길', nightAccidentCount: 6, trafficCount: 89, badLane: 2, riskLevel: 6 },
  { address: '경상북도 포항시 북구 용흥시장로', nightAccidentCount: 3, trafficCount: 4, badLane: 3, riskLevel: 1 },
  { address: '경상북도 포항시 남구 신덕시장길', nightAccidentCount: 2, trafficCount: 6, badLane: 4, riskLevel: 1 },
  { address: '경상북도 포항시 북구 대흥시장길', nightAccidentCount: 45, trafficCount: 6, badLane: 5, riskLevel: 26 },
  { address: '경상북도 포항시 남구 양학시장길', nightAccidentCount: 2, trafficCount: 3, badLane: 6, riskLevel: 1 },
  { address: '경상북도 포항시 북구 용흥해안로', nightAccidentCount: 5, trafficCount: 7, badLane: 6, riskLevel: 3 },
  { address: '경상북도 포항시 남구 대도시장로', nightAccidentCount: 6, trafficCount: 2, badLane: 78, riskLevel: 22 },
  { address: '경상북도 포항시 북구 죽도시장로', nightAccidentCount: 56, trafficCount: 2, badLane: 9, riskLevel: 34 },
  { address: '경상북도 포항시 남구 죽도시장길', nightAccidentCount: 5, trafficCount: 85, badLane: 9, riskLevel: 8 },
  { address: '경상북도 포항시 북구 흥해해안로', nightAccidentCount: 8, trafficCount: 2, badLane: 4, riskLevel: 5 },
  { address: '경상북도 포항시 남구 두호시장길', nightAccidentCount: 9, trafficCount: 84, badLane: 54, riskLevel: 27 },
  { address: '경상북도 포항시 북구 상도시장길', nightAccidentCount: 9, trafficCount: 653, badLane: 2, riskLevel: 27 },
  { address: '경상북도 포항시 남구 우현시장길', nightAccidentCount: 44, trafficCount: 24, badLane: 3, riskLevel: 26 },
  { address: '경상북도 포항시 북구 상도시장로', nightAccidentCount: 3, trafficCount: 8, badLane: 34, riskLevel: 16 },
  { address: '경상북도 포항시 남구 죽도해안길', nightAccidentCount: 2, trafficCount: 263, badLane: 5, riskLevel: 11 },
  { address: '경상북도 포항시 북구 우현해안로', nightAccidentCount: 6, trafficCount: 274, badLane: 6, riskLevel: 14 },
  { address: '경상북도 포항시 남구 청림해안로', nightAccidentCount: 6, trafficCount: 868, badLane: 6, riskLevel: 35 },
  { address: '경상북도 포항시 북구 오천시장로', nightAccidentCount: 7, trafficCount: 235, badLane: 5, riskLevel: 13 },
  { address: '경상북도 포항시 남구 흥해시장로', nightAccidentCount: 8, trafficCount: 746, badLane: 9, riskLevel: 34 },
  { address: '경상북도 포항시 북구 해도해안길', nightAccidentCount: 8, trafficCount: 284, badLane: 3, riskLevel: 14 },
  {
    address: '경상북도 포항시 남구 용흥해안길',
    nightAccidentCount: 43,
    trafficCount: 742,
    badLane: 32,
    riskLevel: 64,
  },
  { address: '경상북도 포항시 북구 대잠시장길', nightAccidentCount: 5, trafficCount: 642, badLane: 3, riskLevel: 25 },
  { address: '경상북도 포항시 남구 장기시장로', nightAccidentCount: 6, trafficCount: 846, badLane: 6, riskLevel: 35 },
  { address: '경상북도 포항시 북구 송도시장로', nightAccidentCount: 7, trafficCount: 24, badLane: 4, riskLevel: 6 },
  { address: '경상북도 포항시 남구 대송시장로', nightAccidentCount: 8, trafficCount: 245, badLane: 2, riskLevel: 26 },
  { address: '경상북도 포항시 북구 흥해시장로', nightAccidentCount: 89, trafficCount: 64, badLane: 1, riskLevel: 55 },
  { address: '경상북도 포항시 남구 장성시장로', nightAccidentCount: 9, trafficCount: 74, badLane: 1, riskLevel: 56 },
  { address: '경상북도 포항시 북구 양학해안로', nightAccidentCount: 9, trafficCount: 87, badLane: 3, riskLevel: 58 },
  {
    address: '경상북도 포항시 남구 두호시장로',
    nightAccidentCount: 3,
    trafficCount: 245,
    badLane: 33,
    riskLevel: 43,
  },
  { address: '경상북도 포항시 북구 상도시장로', nightAccidentCount: 5, trafficCount: 4, badLane: 45, riskLevel: 41 },
  {
    address: '경상북도 포항시 남구 해맞이시장로',
    nightAccidentCount: 3,
    trafficCount: 32,
    badLane: 5,
    riskLevel: 29,
  },
  { address: '경상북도 포항시 북구 흥해시장로', nightAccidentCount: 2, trafficCount: 9, badLane: 3, riskLevel: 10 },
  { address: '경상북도 포항시 남구 장성해안로', nightAccidentCount: 8, trafficCount: 78, badLane: 2, riskLevel: 0 },
  { address: '경상북도 포항시 북구 양학시장로', nightAccidentCount: 9, trafficCount: 334, badLane: 4, riskLevel: 0 },
];
